<a href="https://colab.research.google.com/github/StarBunny007/Intro-to-Torch/blob/main/Tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch2 = torch.arange(20)
X = my_torch2.reshape(-1 ,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [ ]:
Y = my_torch2.reshape(4,-1)
Y

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [ ]:
#additions
tensora = torch.tensor([1,2,3,4])
tensorb = torch.tensor([5,6,7,8])
tensora+tensorb,tensora-tensorb,tensora**tensorb

(tensor([ 6,  8, 10, 12]),
 tensor([-4, -4, -4, -4]),
 tensor([    1,    64,  2187, 65536]))

In [ ]:
import os
print(os.getcwd())
os.makedirs("python")


/content
